version: "3.7"
services:
    restic-rest-server:
        image: restic/rest-server:0.10.0

        networks:
            - default

        restart: always

        volumes:
            - resticRestServerData:/data

volumes:
    resticRestServerData:
        driver: local
