version: "3.7"
services:
    restic-rest-server:
        image: restic/rest-server:0.9.7

        networks:
            - default

        restart: always

        environment:
            OPTIONS: ${RESTIC_REST_SERVER_FLAGS---private-repos}

        volumes:
            - resticRestServerData:/data

volumes:
    resticRestServerData: {}
